"""Add Post, Comment, Follower tables

Revision ID: e4235fbe9e22
Revises: ee9a8d39ef32
Create Date: 2025-04-18 01:26:01.773771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4235fbe9e22'
down_revision = 'ee9a8d39ef32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('comment_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('following_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('follower_user_from_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follower_user_to_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['following_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.drop_column('user_to_id')
        batch_op.drop_column('user_from_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=500), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('caption')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('content')

    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_user_to_id_fkey', 'user', ['user_to_id'], ['id'])
        batch_op.create_foreign_key('follower_user_from_id_fkey', 'user', ['user_from_id'], ['id'])
        batch_op.drop_column('following_id')
        batch_op.drop_column('follower_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comment_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    op.drop_table('media')
    # ### end Alembic commands ###
